version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: paylite-mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      target: production
    container_name: paylite-app
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env                                   # ← Add this line
    environment:
      SPRING_DATASOURCE_URL: ${PAYLITE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${PAYLITE_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PAYLITE_DB_PASSWORD}
      API_KEYS: ${API_KEYS}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
    ports:
      - "8080:8080"

volumes:
  db_data: