spring:
  application:
    name: paylite
  datasource:
    url: jdbc:mysql://${PAYLITE_DB_HOST:localhost}:3306/${MYSQL_DATABASE:paylite}
    username: ${PAYLITE_DB_USERNAME:root}
    password: ${PAYLITE_DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    org.springframework: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationId}] %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  api-keys: ${API_KEYS:default-api-key}
  webhook-secret: ${WEBHOOK_SECRET:default-webhook-secret}