spring:
  application:
    name: paylite
  datasource:
    url: jdbc:mysql://${PAYLITE_DB_HOST:localhost}:3306/${MYSQL_DATABASE:paylite}
    username: ${PAYLITE_DB_USERNAME:root}
    password: ${PAYLITE_DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.zaxxer.hikari: INFO
    org.springframework: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  api-keys: ${API_KEYS:default-api-key}
  webhook-secret: ${WEBHOOK_SECRET:default-webhook-secret}